spring.datasource:
  url: 'jdbc:postgresql://127.0.0.1:5432/'
  #username: postgres
  #password: mysecretpassword

spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

spring.flyway.locations: "db/migration,db/specific/postgres"